# Generated by Django 6.0.5 on 2026-05-25 21:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_cliente', models.CharField(max_length=50)),
                ('telefone', models.CharField(blank=True, max_length=11, null=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['nome_cliente'],
            },
        ),
        migrations.CreateModel(
            name='AlimentoCardapio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_alimento', models.CharField(max_length=50, unique=True)),
                ('descricao', models.TextField(max_length=250)),
                ('foto_alimento', models.ImageField(blank=True, null=True, upload_to='fotoalimento/', verbose_name='foto')),
                ('preco', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Preço')),
                ('disponivel', models.BooleanField(default=True, verbose_name='Disponivel')),
                ('disponivel_estoque', models.IntegerField(default=0, verbose_name='Estoque disponivel:')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Alimentos', to='cardapio.categoria', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'AlimentoCardapio',
                'verbose_name_plural': 'AlimentosCardapio',
                'ordering': ['nome_alimento'],
            },
        ),
    ]
