# Generated by Django 6.0.5 on 2026-05-26 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardapio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alimentocardapio',
            name='disponivel_estoque',
            field=models.PositiveIntegerField(default=0, verbose_name='Estoque disponivel:'),
        ),
    ]
