# Generated by Django 6.0.5 on 2026-05-27 23:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardapio', '0003_pedido'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemPedidos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=5)),
                ('alimento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cardapio.alimentocardapio')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Itens', to='cardapio.pedido')),
            ],
        ),
    ]
