# Generated by Django 6.0.5 on 2026-06-08 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cardapio_app", "0004_itempedidos"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="alimentocardapio",
            name="disponivel_estoque",
        ),
        migrations.AlterField(
            model_name="alimentocardapio",
            name="categoria",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Alimentos",
                to="cardapio_app.categoria",
                verbose_name="Categoria",
            ),
        ),
    ]
