# Generated by Django 6.0.5 on 2026-06-08 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cardapio_app", "0005_remove_alimentocardapio_disponivel_estoque_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="itempedidos",
            options={
                "verbose_name": "Item do Pedido",
                "verbose_name_plural": "Itens do Pedido",
            },
        ),
        migrations.AlterModelOptions(
            name="pedido",
            options={
                "ordering": ["-criado_em"],
                "verbose_name": "Pedido",
                "verbose_name_plural": "Pedidos",
            },
        ),
        migrations.AddField(
            model_name="pedido",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pendente", "Pendente"),
                    ("Preparando", "Preparando"),
                    ("Concluído", "Concluído"),
                ],
                default="Pendente",
                max_length=20,
                verbose_name="Status do Pedido",
            ),
        ),
    ]
