# Generated by Django 6.0.5 on 2026-06-09 23:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "cardapio_app",
            "0006_alter_itempedidos_options_alter_pedido_options_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="itempedidos",
            name="alimento",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="cardapio_app.alimentocardapio",
            ),
        ),
    ]
